[package]
name = "gen-01-particles-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
noise = { version = "0.8.2", features = ["image", "images"] }
itertools.workspace = true
